### ISSUE TITLE
Using V2 entity system for English

### ISSUE THREAD

**Issue by dorringel** [ibm-cloud-docs/natural-language-understanding#56]
Maybe I'm missing something, but I can't find a version for English that uses the "Version 2 entity type system".

Going over the documentation here:
https://cloud.ibm.com/docs/services/natural-language-understanding?topic=natural-language-understanding-entity-type-systems#entity-type-systems

all versions have Version-1 under English language.

**Comment by g-may** [comment]
Hey @dorringel, sorry that this went so long without a response. If you're still wondering about the English entity type system, it has not switched to the Version 2 type system. The service uses the Version 1 type system for English text.
