### ISSUE TITLE
blabla

### ISSUE THREAD

**Issue by brachash** [ibm-cloud-docs/natural-language-understanding#61]
$ curl -X POST -u "apikey:{nlu}" \
"{concer}/v1/analyze?version=2018-11-16" \
--header "Content-Type: application/json" \
--data '{
  "url": "http://newsroom.ibm.com/Guerbet-and-IBM-Watson-Health-Announce-Strategic-Partnership-for-Artificial-Intelligence-in-Medical-Imaging-Liver",
  "features": {
    "sentiment": {},
    "categories": {},
    "concepts": {},
    "entities": {},
    "keywords": {}
  }
}'

**Comment by g-may** [comment]
hey @brachash, could you please explain what you're having trouble with?
