### ISSUE TITLE
Error Code 422

### ISSUE THREAD

**Issue by gracelegrand** [ibm-cloud-docs/natural-language-understanding#68]
Receiving Error Code 422 stating there is not enough text for language id. I am unable to detect which part of the API feature this refers to due to this error and I cannot find documentation on the minimum amount of words allowed for the NLU API. 
<img width="471" alt="Screen Shot 2020-04-27 at 8 57 00 AM" src="https://user-images.githubusercontent.com/60152288/80374775-35912300-8865-11ea-8c1d-db91f765c2df.png">

**Comment by SirSpidey** [comment]
@gracelegrand See the [troubleshooting topic](https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-troubleshooting#incorrect-language-detection)
> The automatic language detection might not be accurate for text that contains fewer than 100 characters. If the service doesn't detect the correct language of your text, you can [override automatic language detection](https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-overriding-language-detection).

So try specifying the `language` in your request. You can see information for various programming languages at https://cloud.ibm.com/apidocs/natural-language-understanding#analyze-text
