### ISSUE TITLE
Entity API versioning

### ISSUE THREAD

**Issue by ivar-os** [ibm-cloud-docs/natural-language-understanding#71]
On page https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-entity-type-systems Entity type systems for different versions are described (last version 2018-11-16).

In the examples of the API documentation, version 2019-07-12 is used. I can't find this version in the documentation. Can you explain how this works?

**Comment by SirSpidey** [comment]
Hi @ivar-os 
`version` is a parameter on API calls. See the information in the [release notes](https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-release-notes#service-api-versioning) and in the [API ref](https://cloud.ibm.com/apidocs/natural-language-understanding#versioning)
