### ISSUE TITLE
the provided category list has a wrong category

### ISSUE THREAD

**Issue by YukiAsaiJerome** [ibm-cloud-docs/natural-language-understanding#74]
The provided category list on the page below includes a wrong category.
https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-categories-hierarchy&locale=en

This is the detail.
●a wrong category in the excel
/society/crime/sexual offen**s**e
 
●a category that you actually get in the NLU result
/society/crime/sexual offen**c**e

**Comment by kmacdonald06** [comment]
The Categories type system has since been updated with NLU version 2021-08-15: https://cloud.ibm.com/docs/natural-language-understanding?topic=natural-language-understanding-categories-hierarchy
