### ISSUE TITLE
Unable to import ClassificationsOptions

### ISSUE THREAD

**Issue by vera-nan** [ibm-cloud-docs/natural-language-understanding#78]
I am unable to import ClassificationsOptions from the libraries:

from ibm_watson.natural_language_understanding_v1 import Features, ClassificationsOptions
ImportError: cannot import name 'ClassificationsOptions' from 'ibm_watson.natural_language_understanding_v1'

**Comment by SirSpidey** [comment]
Hi @vera-nan,

I'm not sure which Watson SDK you're referring to, but here are 2 thoughts:

- Make sure that you installed the latest version of the SDK. 
- Make sure you're calling the imports correctly. I've included the code for Python and Ruby here

**Python** 
```python
from ibm_watson import NaturalLanguageUnderstandingV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
```

**Ruby**
```ruby
require "ibm_watson/natural_language_understanding_v1"
include IBMWatson
```

See the API reference for Python: [Create classifications model](https://cloud.ibm.com/apidocs/natural-language-understanding?code=python#createclassificationsmodel). If you have other issues, consider posting an issue directly in th SDK repo. The link is available in the introduction of the API ref for the language or framework that you're using.
