### ISSUE TITLE
Invalid Route for training category

### ISSUE THREAD

**Issue by AliAhmedNada** [ibm-cloud-docs/natural-language-understanding#84]
I am training to Train category model and it is failing for some reason , is it totally down ?! 

![Screenshot 2023-04-29 110559](https://user-images.githubusercontent.com/17008257/235292062-bbefb6f6-8c0c-418a-b015-9fc241a50285.png)

**Comment by AliAhmedNada** [comment]
I am in europe region

**Comment by AliAhmedNada** [comment]
it works in dallas only

**Comment by mingl1** [comment]
Thank you so much for sharing that it works in Dallas region only!
